project_name: axiom-syslog-proxy

builds:
  - <<: &build_defaults
      binary: axiom-syslog-proxy
      main: ./cmd/axiom-syslog-proxy
      env:
        - CGO_ENABLED=0
      tags:
        - osusergo
        - netgo
        - static_build
      flags:
        - -buildvcs=false
        - -buildmode=pie
        - -installsuffix=cgo
        - -trimpath
      ldflags:
        - -s -w -extldflags "-fno-PIC -static -Wl -z now -z relro"
        - -X github.com/axiomhq/pkg/version.release={{ .Version }}
        - -X github.com/axiomhq/pkg/version.revision={{ .ShortCommit }}
        - -X github.com/axiomhq/pkg/version.buildDate={{ .CommitDate }}
        - -X github.com/axiomhq/pkg/version.buildUser=goreleaser
      mod_timestamp: "{{ .CommitTimestamp }}"
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - <<: *build_defaults
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - <<: *build_defaults
    flags:
      - -buildvcs=false
      - -buildmode=exe
      - -installsuffix=cgo
      - -trimpath
    id: linux-no-pie
    goos:
      - linux
    goarch:
      - arm
      - 386
    goarm:
      - 6
      - 7

  - <<: *build_defaults
    flags:
      - -buildvcs=false
      - -buildmode=exe
      - -installsuffix=cgo
      - -trimpath
    id: docker
    goos:
      - linux
    goarch:
      - amd64

  - <<: *build_defaults
    id: windows
    goos:
      - windows
    goarch:
      - amd64
      - 386

archives:
  - <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: nix
    builds:
      - darwin
      - linux
      - linux-no-pie
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - README.md
  - <<: *archive_defaults
    id: windows
    builds:
      - windows
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

milestones:
  - repo:
      owner: axiomhq
      name: axiom-syslog-proxy
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: axiom-syslog-proxy
  prerelease: auto
  name_template: "Axiom Syslog Proxy v{{ .Version }}"

brews:
  - name: axiom-syslog-proxy
    description: Syslog ingestion by proxy for Axiom
    homepage: https://axiom.co
    license: MIT
    repository:
      owner: axiomhq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: axiom-automation
      email: hello@axiom.co
    skip_upload: auto
    folder: Formula
    install: bin.install "{{ .ProjectName }}"
    test: assert_match "x", "x"

dockers:
  - ids:
      - docker
    image_templates:
      - "docker.io/axiomhq/axiom-syslog-proxy:{{ .Major }}"
      - "docker.io/axiomhq/axiom-syslog-proxy:{{ .Major }}.{{ .Minor }}"
      - "docker.io/axiomhq/axiom-syslog-proxy:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "docker.io/axiomhq/axiom-syslog-proxy:latest"
      - "ghcr.io/axiomhq/axiom-syslog-proxy:{{ .Major }}"
      - "ghcr.io/axiomhq/axiom-syslog-proxy:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/axiomhq/axiom-syslog-proxy:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/axiomhq/axiom-syslog-proxy:latest"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://axiom.co
      - --label=org.opencontainers.image.source=https://github.com/axiomhq/axiom-syslog-proxy
      - --label=org.opencontainers.image.documentation=https://github.com/axiomhq/axiom-syslog-proxy
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.author=Axiom, Inc. <info@axiom.co>
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.vendor=Axiom, Inc.
